name: Build Pull Request
permissions:
  contents: read
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  build:
    strategy:
      matrix:
        tc: [ 8, 17, 21, 25 ]
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      TARGET_COMPATIBILITY: ${{ matrix.tc }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Nats Server
        run: |
          pkill -9 nats-server 2>/dev/null || true
          mkdir -p ~/.local/bin
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go build -o ~/.local/bin/nats-server
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test jacocoTestReport
      - name: Verify Javadoc
        run: ./gradlew javadoc
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel: true
          flag-name: tc${{ matrix.tc }}
      - name: Clean up
        if: always()
        run: pkill -9 nats-server 2>/dev/null || true

  coveralls-finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finish
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          carryforward: "tc8"